ALTER TABLE orders ADD COLUMN IF NOT EXISTS subtotal_amount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount DOUBLE PRECISION DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_latitude DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_longitude DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS scheduled_slot VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS contact_name VARCHAR(255);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_partner VARCHAR(100);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_charge DOUBLE PRECISION DEFAULT 0;
